### ISSUE TITLE
!lmgtfy Command

### ISSUE THREAD

**Issue by Webd01** [My-Darling-Web/MDWBot#5]
The goal of this command is to send a ``lmgtfy`` link. 

Just like that: ``!lmgtfy what's the meaning of life?``

> The bot should send this link: [http://www.lmgtfy.com/?q=what%27s+the+meaning+of+life%3F](http://www.lmgtfy.com/?q=what%27s+the+meaning+of+life%3F)

Also, it would be great to be able to mention a specific user.

**Comment by dimensi0n** [comment]
I'll do it

**Comment by Webd01** [comment]
Thanks! Waiting for your PR :)
